CREATE TABLE PERSON (
	ID INT NOT NULL PRIMARY KEY IDENTITY, -- იდენტიფიკატორი
	FIRSTNAME NVARCHAR(50) NOT NULL, -- სახელი
	LASTNAME NVARCHAR(50) NOT NULL, -- გვარი
	GENDER INT NOT NULL, -- სქესი
	IDNUM CHAR(11) NOT NULL, -- პირადი ნომერი
	DATEOFBIRTH DATE NOT NULL, -- დაბადების თარიღი
);

Create Table PHONE (
	ID INT NOT NULL PRIMARY KEY IDENTITY, -- იდენტიფიკატორი
	TYPE INT NOT NULL, -- ტელეფონის ნომრის ტიპი
	NUMBER NVARCHAR(50), -- ნომერი
	PERSONID INT, -- ფიზიკური პირი
	CONSTRAINT FK_PERSON_PHONE FOREIGN KEY (PERSONID) REFERENCES PERSON(Id) -- Foreign key შეზღუდვა
);

Create Table PERSONALRELATIONS (
	ID INT NOT NULL PRIMARY KEY IDENTITY, -- იდენტიფიკატორი
	PERSONID INT NOT NULL, -- ფიზიკური პირი
	RELATEDPERSONID INT NOT NULL, -- ფიზიკური პირი
	TYPE INT NOT NULL, -- კავშირის ტიპი
	CONSTRAINT UC_PERSON_RELATION UNIQUE (PERSONID, RELATEDPERSONID, TYPE),  -- უნიკალურობის შეზღუდვა
    CONSTRAINT FK_PERSON_PERSONID FOREIGN KEY (PERSONID) REFERENCES PERSON(Id),    -- Foreign key შეზღუდვა
    CONSTRAINT FK_PERSON_RELATEDPERSONID FOREIGN KEY (RELATEDPERSONID) REFERENCES PERSON(Id) -- Foreign key შეზღუდვა
);

Create Table ERRORLOG (
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	REQUESTTIME DATETIME NOT NULL,
	REQUESTBODY NVARCHAR(1500),
	IPADDRESS NVARCHAR(50) NOT NULL,
	METHOD NVARCHAR(50) NOT NULL,
	ARGUMENTS NVARCHAR(1500),
	ERRORMESSAGE NVARCHAR(500) NOT NULL
);